---
abstract: 'Inside out objects for Moo'
author:
  - 'haarg - Graham Knop (cpan:HAARG) <haarg@haarg.org>'
build_requires:
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooX-InsideOut
no_index:
  directory:
    - t
    - inc
requires:
  Hash::Util::FieldHash::Compat: 0.03
  Moo: 1.000007
  perl: 5.8
  strictures: 1
resources:
  homepage: http://github.com/haarg/MooX-InsideOut
  repository: git://github.com/haarg/MooX-InsideOut.git
version: 0.001001
